baseurl = ""
languageCode = "zh-CN"
paginate = 6
theme = "hugo-tania"
title = "Nukiyoam's Blog"

[params]
# Emoji will show before the blog title on site navbar.
titleEmoji = "🧑‍💻"

# Logo will show before the blog title on site navbar.
titleLogo = ""

# Enable float footnotes.
# Default to true
enableFootnotes = true

author = "nukiyoam"
siteDesc = "Hugo is Absurdly Fast!"
siteName = "Nukiyoam's Blog"

[params.colorScheme]
# Enable toggle colorScheme
# Default to true
toggle = true
# Default colorScheme
# Default to auto
default = "auto"
# Limit how many categories filter show above search input.
# Default to 5
maxCategoryToShow = 10

# Show your social information with icon on index bio with `_index.md` content.
[params.socialOptions]
dev-to = ""
email = "yikun.mao@gmail.com"
facebook = ""
github = "https://github.com/nukiyoam"
instagram = ""
linkedin = ""
medium = ""
stack-overflow = ""
steam = ""
telegram = ""
twitch = ""
twitter = ""
whatsapp = ""

# Comments settigns
[params.comments]
enabled = true
provider = "giscus"

[params.comments.giscus]
lazyLoading = true
theme = "dark"
# default to pathname, do not support specific term or number now
# options: url, title, og:title
mapping = "pathname"
# 1 means true, 0 means false
# default to 1
reactionsEnabled = 1
# default to 0
emitMetadata = 0
lang = "zh-CN"

[params.comments.giscus.repo]
id = "R_kgDOHTf3Ow"
name = "nukiyoam/blog"

[params.comments.giscus.category]
id = "DIC_kwDOHTf3O84CYEjN"
name = "Announcements"



[menu]
[[menu.header]]
name = "Articles"
url = "/articles/"

[[menu.footer]]
name = "RSS"
url = "/index.xml"

[markup]
[markup.highlight]
lineNos = true
noClasses = false
[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "RSS", "JSON"]
